name = "ReverseDiffExpressionsBase"
uuid = "6c4e8705-acc8-45e6-99c7-2e34d4f10b96"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMDPirates = "21efa798-c60a-11e8-04d3-e1a92915a26a"
StackPointers = "062a3e2c-34b1-4659-9cae-7af421e0d832"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
SIMDPirates = "0"
StackPointers = "0"
VectorizationBase = "0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
